### Editing this file for font customization is strongly discouraged.
### Use `private-build-plans.toml` to create custom fonts.
### Changing the numbers may make the builder crash / hang / produce broken shapes.

[iosevka]
copyright = 'Copyright (c) 2015-2020 Belleve Invis.'
licence = '''This font software is licenced under the SIL Open Font Licence, Version 1.1. This is licence is avaliable with a FAQ at: http://scripts.sil.org/OFL. This font software is distributes on an 'AS IS' basis, without warranties or conditions of any kind, either express or implied. See the SIL Open Font licence fot the specific language, premissions and limitations governing your use of this font software.'''
manufacturer = 'Belleve Invis'
designer = 'Belleve Invis'
description = 'Spatial efficient monospace font family for programming. Built from code. http://be5invis.github.io/Iosevka'

leading = 1250     # Default line height times 1000.
descenderPad = 0   # Additional line height, added to descender.
width = 500        # Character width. DON'T EDIT THIS. Use `wd-#` selectors below.
cap = 735          # Cap height (as well as ascender).
xheight = 530      # X-height.
#descender = -205  # Depth of descender. Currently unused.
winMetricAscenderPad  = 0 # Padding of Win ascnder metrics to avoid clipping. See #343
winMetricDescenderPad = 0 # Padding of Win descender metrics to avoid clipping. See #343

symbolMid = 340    # Center of parens, maths, geometrics...
parenSize = 966    # Size of parens, brackets, braces, slashes, etc.
operSize = 0.80    # Size of mathematical operators (cups, etc.)
tackSize = 0.80    # Size of logical operators (tacks, etc.)
bgopSize = 1.10    # Size of "taller" mathematical operators
plusSize = 0.52    # Size of plus and arith symbols
pictSize = 1.10    # Size of pictograms
arrowHeight = 1.50 # Height of arrows

contrast = 1.11111 # Stroke width contrast.

slantAngle = 0     # Slant angle, in degrees.

accent = 155       # Height of accent marks.
accentx = 200      # Width of accent marks.
overshoot = -8     # Vertical overshoot for arcs.
overshootx = -8    # Horizontal overshoot for arcs.
oxhook = -2        # Horizontal overshoot for hook tips.
fovershoot = -40   # Overshoot of the top end of italic `f`.

shoulderfineMin = 0.8

isItalic = false   # Use italic shapes?
isOblique = false  # Use oblique shapes?

spacing = 1        # Spacing indicator

# Powerline-specific parameters
powerlineScaleY = 1 # Vertical scale
powerlineScaleX = 1 # Horizontal scale
powerlineShiftY = 0 # Vertical shift
powerlineShiftX = 0 # Horizontal shift

# Diversity widths
diversityM = 1
diversityF = 1
diversityI = 1
diversityII = 1

# Whether to generate CV-SS features
enableCvSs = true

# Whether to generate ligation
enableLigation = true

# Excluded code points
excludedCharRanges = []

[verbose]
verbose = true

###### Slab variant
[slab]
slab = true
onebalance = 10
overshootx = -16
[slab.multiplies]
sb = 1.1

###### Spacings
# Terminal variant
[sp-term]
spacing = 0

# "FontFonfig Monospace"
[sp-force-monospace]
spacing = 0
forceMonospace = true

# Fixed variant
[sp-fixed]
spacing = 0
enableLigation = false
forceMonospace = true

###### Disabling Ligation
[no-ligation]
enableLigation = false
[nolig] # For compatibility
enableLigation = false

###### Disabling CV/SS
[no-cv-ss]
enableCvSs = false

###### Slantness
[s-italic]
isItalic = true
slantAngle = 10
jhook = 120

[s-oblique]
isOblique = true
slantAngle = 10
jhook = 120

###### Diversity
[diversity-1]
diversityM = 1.25
diversityF = 1.00
diversityI = 0.75
diversityII = 0.75

[diversity-2]
diversityM = 1.25
diversityF = 0.75
diversityI = 0.75
diversityII = 0.5

###################################################################################################
### Blendable Options

###### Weight

[shapeWeight.blend.400]
stroke = 72       # Primary stroke width
sb = 60           # Primary sidebearings
essx = 1.12       # Proportion of widen of center of "S"
dotsize = 125     # Size of dots
periodsize = 140  # Size of period

jut = 85          # Length of slab serif
vjut = 145        # Length of vertical slab serif
longjut = 175      # Length of long serifs, like that in `i`.

smooth = 195             # Vertical arc size in capital letters.
smallsmooth = 200        # Vertical arc size in lowercase letters.
superness = 2.275        # Superness of arcs.
tightHookSuperness = 2.3 # superness of tight hooks

fbarStrokeAdj = 0.25 # Portion of the fill above the f-bar position

rbalance = 60
rbalance2 = 15
tbalance = 50
tbalance2 = 30
jbalance = 63
fbalance = 6
onebalance = 30

hook  = 155        # Hook depth in most letters.
ahook = 130
shook = 110
jhook = 135
fhook = 120
hookx = 170
rhook = 110

cthin = 0.75
cthinb = 0.5
vtipfine = 0.8
vtipfineSlab = 0.9

[shapeWeight.blend.100]
jut = 70
vjut = 145
smooth = 195
rhook = 110
rbalance = 60
rbalance2 = 15
cthin = 0.9
cthinb = 0.9
vtipfine = 1
vtipfineSlab = 1
stroke = 18
sb = 72
dotsize = 53
periodsize = 55

[shapeWeight.blend.200]
jut = 75
vjut = 145
smooth = 195
rhook = 110
rbalance = 60
rbalance2 = 15
cthin = 0.75
cthinb = 0.75
vtipfine = 1
vtipfineSlab = 1
stroke = 36
sb = 68
dotsize = 70
periodsize = 77

[shapeWeight.blend.300]
jut = 80
vjut = 145
smooth = 195
rhook = 110
rbalance = 60
rbalance2 = 15
cthin = 0.75
cthinb = 0.5
vtipfine = 0.9
vtipfineSlab = 0.9
stroke = 56
sb = 64
dotsize = 100
periodsize = 115

[shapeWeight.blend.500]
essx = 1.12
jut = 85
vjut = 157
smooth = 200
rhook = 110
rbalance = 60
rbalance2 = 15
stroke = 84
sb = 57
dotsize = 135
periodsize = 160

[shapeWeight.blend.600]
essx = 1.07
jut = 85
vjut = 170
smooth = 203
rhook = 110
rbalance = 55
rbalance2 = 20
stroke = 97
sb = 54
dotsize = 145
periodsize = 168

[shapeWeight.blend.700]
essx = 1.06
jut = 89
vjut = 179
smooth = 206
rhook = 95
rbalance = 52
rbalance2 = 23
stroke = 106
sb = 50
dotsize = 157
periodsize = 180

[shapeWeight.blend.800]
essx = 1.05
jut = 96
vjut = 189
smooth = 210
rhook = 97
rbalance = 50
rbalance2 = 25
stroke = 116
sb = 45
dotsize = 167
periodsize = 188

[shapeWeight.blend.900]
essx = 1.03
jut = 100
vjut = 199
smooth = 215
rhook = 105
rbalance = 50
rbalance2 = 25
stroke = 126
sb = 42
dotsize = 180
periodsize = 200

###### Widths
[shapeWidth.multiplies.blend.500]
width        = 1
stroke       = 1
sb           = 1
jut          = 1
longjut      = 1
rhook        = 1
rbalance     = 1
tbalance     = 1
smallsmooth  = 1

[shapeWidth.multiplies.blend.664]
width        = 1.328 # 664 for normal char
stroke       = 1.103 # Make strokes a little thicker
sb           = 1.777
jut          = 1.323
longjut      = 1.323
rhook        = 1.323
rbalance     = 1.236
tbalance     = 1.210
smallsmooth  = 1.103

[shapeWidth.multiplies.blend.618]
width        = 1.236 # 618 for normal char
stroke       = 1.075 # Make strokes a little thicker
sb           = 1.539
jut          = 1.233
longjut      = 1.233
rhook        = 1.233
rbalance     = 1.236
tbalance     = 1.154
smallsmooth  = 1.075

[shapeWidth.multiplies.blend.576]
width        = 1.152 # 576mem for normal char
stroke       = 1.050 # Make strokes a little thicker
sb           = 1.333
jut          = 1.150
longjut      = 1.150
rhook        = 1.150
rbalance     = 1.152
tbalance     = 1.100
smallsmooth  = 1.050

[shapeWidth.multiplies.blend.537]
width        = 1.074 # 537mem for normal char
stroke       = 1.023 # Make strokes a little thicker
sb           = 1.154
jut          = 1.072
longjut      = 1.072
rhook        = 1.072
rbalance     = 1.074
tbalance     = 1.049
smallsmooth  = 1.023

[shapeWidth.multiplies.blend.466]
width        = 0.932 # 466mem for normal char
stroke       = 0.975
sb           = 0.866
jut          = 0.933
longjut      = 0.933
rhook        = 1
rbalance     = 0.931
tbalance     = 0.953
smallsmooth  = 0.975

[shapeWidth.multiplies.blend.434]
width        = 0.868 # 434mem for normal char
stroke       = 0.952
sb           = 0.750
jut          = 0.870
longjut      = 0.870
rhook        = 1
rbalance     = 0.868
tbalance     = 0.909
smallsmooth  = 0.952

###################################################################################################
### Metric-override hives
### These hives are now discouraged in favor of 'metric-override' in build plans but they are
### still supported in version 3.x.

###### Leading
[leading-750]
leading = 750
[leading-1000]
leading = 1000
[leading-1250]
leading = 1250
[leading-1500]
leading = 1500
[leading-1750]
leading = 1750
[leading-2000]
leading = 2000

###### Win metric pad
[win-metric-pad-0]
winMetricAscenderPad = 0
winMetricDescenderPad = 0
[win-metric-pad-50]
winMetricAscenderPad = 50
winMetricDescenderPad = 50
[win-metric-pad-100]
winMetricAscenderPad = 100
winMetricDescenderPad = 100
[win-metric-pad-150]
winMetricAscenderPad = 150
winMetricDescenderPad = 150
[win-metric-pad-200]
winMetricAscenderPad = 200
winMetricDescenderPad = 200
[win-metric-pad-250]
winMetricAscenderPad = 250
winMetricDescenderPad = 250
[win-metric-pad-300]
winMetricAscenderPad = 300
winMetricDescenderPad = 300

###### Powerline
[powerline-scale-y-750]
powerlineScaleY = 0.75
[powerline-scale-y-875]
powerlineScaleY = 0.875
[powerline-scale-y-1000]
powerlineScaleY = 1
[powerline-scale-y-1125]
powerlineScaleY = 1.125
[powerline-scale-y-1250]
powerlineScaleY = 1.25
[powerline-scale-y-1375]
powerlineScaleY = 1.375
[powerline-scale-y-1500]
powerlineScaleY = 1.5
[powerline-scale-x-750]
powerlineScaleX = 0.75
[powerline-scale-x-875]
powerlineScaleX = 0.875
[powerline-scale-x-1000]
powerlineScaleX = 1
[powerline-scale-x-1125]
powerlineScaleX = 1.125
[powerline-scale-x-1250]
powerlineScaleX = 1.25
[powerline-scale-x-1375]
powerlineScaleX = 1.375
[powerline-scale-x-1500]
powerlineScaleX = 1.5
[powerline-shift-y-n500]
powerlineShiftY = -500
[powerline-shift-y-n450]
powerlineShiftY = -450
[powerline-shift-y-n400]
powerlineShiftY = -400
[powerline-shift-y-n350]
powerlineShiftY = -350
[powerline-shift-y-n300]
powerlineShiftY = -300
[powerline-shift-y-n250]
powerlineShiftY = -250
[powerline-shift-y-n200]
powerlineShiftY = -200
[powerline-shift-y-n150]
powerlineShiftY = -150
[powerline-shift-y-n100]
powerlineShiftY = -100
[powerline-shift-y-n50]
powerlineShiftY = -50
[powerline-shift-y-0]
powerlineShiftY = 0
[powerline-shift-y-p50]
powerlineShiftY = 50
[powerline-shift-y-p100]
powerlineShiftY = 100
[powerline-shift-y-p150]
powerlineShiftY = 150
[powerline-shift-y-p200]
powerlineShiftY = 200
[powerline-shift-y-p250]
powerlineShiftY = 250
[powerline-shift-y-p300]
powerlineShiftY = 300
[powerline-shift-y-p350]
powerlineShiftY = 350
[powerline-shift-y-p400]
powerlineShiftY = 400
[powerline-shift-y-p450]
powerlineShiftY = 450
[powerline-shift-y-p500]
powerlineShiftY = 500
[powerline-shift-x-n500]
powerlineShiftX = -500
[powerline-shift-x-n450]
powerlineShiftX = -450
[powerline-shift-x-n400]
powerlineShiftX = -400
[powerline-shift-x-n350]
powerlineShiftX = -350
[powerline-shift-x-n300]
powerlineShiftX = -300
[powerline-shift-x-n250]
powerlineShiftX = -250
[powerline-shift-x-n200]
powerlineShiftX = -200
[powerline-shift-x-n150]
powerlineShiftX = -150
[powerline-shift-x-n100]
powerlineShiftX = -100
[powerline-shift-x-n50]
powerlineShiftX = -50
[powerline-shift-x-0]
powerlineShiftX = 0
[powerline-shift-x-p50]
powerlineShiftX = 50
[powerline-shift-x-p100]
powerlineShiftX = 100
[powerline-shift-x-p150]
powerlineShiftX = 150
[powerline-shift-x-p200]
powerlineShiftX = 200
[powerline-shift-x-p250]
powerlineShiftX = 250
[powerline-shift-x-p300]
powerlineShiftX = 300
[powerline-shift-x-p350]
powerlineShiftX = 350
[powerline-shift-x-p400]
powerlineShiftX = 400
[powerline-shift-x-p450]
powerlineShiftX = 450
[powerline-shift-x-p500]
powerlineShiftX = 500

# Compatibility PUA ligature sample
# [[iosevka.compLig]]
# unicode = 57600 # 0xE100
# featureTag = 'XV00'
# sequence = '<*>'

# Exclude code points
[exclude-check-and-cross-symbol.appends]
excludedCharRanges = [[10003, 10008]]
